### ISSUE TITLE
y-size

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OscamStatus#10]
About FullHD:
- You must always set all lists y-size divisible by itemHeight without the rest.
- and then bottom line set 2px down to y end of list.
- Increase file for Type in All readers.

**Comment by pr2git** [comment]
Can you please provide a patch to fix this?

**Comment by pr2git** [comment]
Done:
https://github.com/E2OpenPlugins/e2openplugin-OscamStatus/commit/308fafd1ccb45fdab3c40614c9a238f65c9b7279
