### ISSUE TITLE
OscamStatus v1.3.1 SSL Fix

### ISSUE THREAD

**Issue by Token2K** [E2OpenPlugins/e2openplugin-OscamStatus#20]
Patched OscamStatus Plugin v1.3.1 (git Version) to eliminate errors with SSL secured Oscam!
 
File: plugin.py
 
old:
import ssl
 
new:
import ssl
try:                                    
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:                                               
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass                                                             
else:                                                                
    # Handle target environment that doesn't support HTTPS verification         
    ssl._create_default_https_context = _create_unverified_https_context
from urllib import unquote_plus                                         
from urllib2 import Request, urlopen, URLError, HTTPError

the patch itself is not from me, but from the Dev's of the Dreambox-Forum!

Best Regards

**Comment by Token2K** [comment]
[plugin.py.zip](https://github.com/E2OpenPlugins/e2openplugin-OscamStatus/files/7651932/plugin.py.zip)

**Comment by pr2git** [comment]
Thanks included into:
https://github.com/E2OpenPlugins/e2openplugin-OscamStatus/pull/21
