### ISSUE TITLE
polish translation - please fix of typo

### ISSUE THREAD

**Issue by mansonpl** [E2OpenPlugins/e2openplugin-OscamStatus#26]
Hi,

I am asking for a typo in the polish translation - in line 290 of OscamStatus.po or maybe in other file, too:
`msgstr "pokaż podłłączonych klientów"`

It should be like this:
`msgstr "pokaż podłączonych klientów"`

Thank you in advance
mpl

**Comment by mansonpl** [comment]
Hi,

I installed OscamStatus from this github and still show typo in the polish tranlsation ""pokaż podłłączonych klientów" - it should be "pokaż podłączonych klientów"

![foto](https://user-images.githubusercontent.com/76478214/166439257-097f9d9c-35ba-46ae-8bf1-e72365fcfa81.jpg)

**Comment by WanWizard** [comment]
As you can see in the commit, it is clearly changed. 

What have you exactly installed, and did you restart Enigma after you did that?

**Comment by WanWizard** [comment]
Language files need to be compiled, the "po" is the source that I updated, the "mo" file is the compiled version.

So you can't just copy it, you need to build the mo files (which is done as part of the image building process). If you want to do it manually, there are plenty of examples on Google, even online services than can do that for you.

**Comment by WanWizard** [comment]
mo files don't belong in source repositories. I don't know who added them, but we don't maintain them, never done.
