### ISSUE TITLE
New server cannot be added

### ISSUE THREAD

**Issue by mansonpl** [E2OpenPlugins/e2openplugin-OscamStatus#27]
Hi,

In image OpenATV 7.1 with python 3.10 I can't add new server in oscamstatus 1.3.3.

In configuration when I manually enter all the data of my second server and press SAVE, an error appears (my enigma2 crashed - blue screen).

Please fix it.

**Comment by mansonpl** [comment]
Hi,

I'm pasting logs from this error:

> 15:25:32.7766   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 238, in action
15:25:32.7796   File "/usr/lib/enigma2/python/Plugins/Extensions/OscamStatus/OscamStatusSetup.py", line 534, in Save
15:25:32.7829     writeCFG(oscamServers)
15:25:32.7829   File "/usr/lib/enigma2/python/Plugins/Extensions/OscamStatus/OscamStatusSetup.py", line 238, in writeCFG
15:25:32.7835     cfg = file(CFG, "w")
15:25:32.7837 NameError: name 'file' is not defined. Did you mean: 'filter'?
15:25:32.7838 [ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap object at 0xabe57f70>>,('ColorActions', 'green')) failed)

Please fix this errors.

regards
mpl

**Comment by Hains** [comment]
https://github.com/E2OpenPlugins/e2openplugin-OscamStatus/commit/0004ed50f79a97c51007306550fbe699b53f038d

**Comment by mansonpl** [comment]
Thank you very much.
Now is working very well.

regards
mpl
