### ISSUE TITLE
Some notes

### ISSUE THREAD

**Issue by ims21** [E2OpenPlugins/e2openplugin-OscamStatus#5]
1) .cfg in plugin's directory ? Why not in /etc/enigma ... automaticaly works with autobackup

2) could be changed white text in yellow buttons ? I know, that there are black contours, but it is not enough ... try set grey text for yellow

**Comment by pr2git** [comment]
1.1 there is now normally no more need for configuration file with the autoconf feature now included.
1.2 the configuration will now be saved into /etc/enigma2/oscamstatus.cfg (I also change its name to all letters lowercase).

2. I agree (still to be done)

**Comment by pr2git** [comment]
Check the Full HD skin I think that now yellow buttons are readable.
